services:
  backend:
    container_name: Ginku_backen
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PORT=3000
      - APIKEY=${APIKEY}
    networks: [ginku, caddy_net]
    expose:
      - '3000'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://localhost:3000/health']
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    container_name: Ginku_front
    build:
      context: .
      dockerfile: front/Dockerfile
    networks: [ginku, caddy_net]
    expose:
      - '5173'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://localhost:5173/']
      interval: 10s
      timeout: 3s
      retries: 10

networks:
  ginku:
    driver: bridge
  caddy_net:
    external: true
