packages:
  - front
  - backend

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

publicHoistPattern:
  - '@ionic/cli-framework-output'

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
